### ISSUE TITLE
Move connection information into a separate file

### ISSUE THREAD

**Issue by aazaff** [paleobot/pbdbUpload-api#17]
Request from PBDB team to move connection information (database host, username, and password) into a separate configuration file, so that the installer can rewrite that file according to the values specified during the installation process.

**Comment by NoisyFlowers** [comment]
There is now a file called env_template in the top level directory. In that file are all (I think) the parameters that must be set for this api. Copy it to a file called .env and set them there.

This is in 
75a44bbf04753b6efe378714e9d47d810dd9a11e
b12122597760d392b002554f65400c5d80cd817f
7ed5d03c390cdf65b4bab41b3e50a6622a55548c
e7cd2605c0eeff62db315f57b0da2bfbe3392489
e1253056bdcf12aab72a506244fa93fbc24ab577

**Comment by NoisyFlowers** [comment]
Had to add another parameter, PORT_DISPLAY, to control whether to display the port in generated urls.

This is in 658845669130ddd0e8461c376762c012a2cdda7b

**Comment by NoisyFlowers** [comment]
Also, for docker, the env file must be located in the paleobiodb directory and must be specified by adding an env_file parameter to pbdbdupload in docker-compose.override.yml:
```
  pbdbupload:
    restart: always
    image: pbdbupload
    build:
      context: /home/ec2-user/repos/pbdbUpload-api
      dockerfile: /home/ec2-user/repos/pbdbUpload-api/Dockerfile
    extra_hosts:
        - host.docker.internal:host-gateway
    environment:
      NODE_ENV: production
    env_file: ".env"
    ports:
      - 5500:5500
```
